### ISSUE TITLE
Connector not accepting `$PORT` and `$IP` as parameters

### ISSUE THREAD

**Issue by theblacksquid** [OpenBazaar/openbazaar-connector#1]
I'm using a Cloud9 hosted workspace, and I'm trying to query the contract I've set up on the store that I have running on that workspace using

    var connector = require('openbazaar-connector')('$IP', '$PORT');

    connector.query_contracts(
        function(data) {
            console.log(summarize(data));
        }
    );

    function summarize(data) {
        return JSON.stringify(data);
    }

It returns this [error](https://gist.github.com/theblacksquid/6a82bbe495ccf433633d).

In Cloud9, your running web apps need to have `$PORT` and `$IP` as their port and ip addresses respectively in order to run successfully. 
I got my OB instance running using [these instructions](http://www.reddit.com/r/OpenBazaar/comments/36srci/installing_and_running_ob_on_cloud9/)

**Comment by theblacksquid** [comment]
BTW, I also ran the included `sample_usage.js` file with `node sample_usage.js $PORT` and it worked fine, it returned a JSON blob of the related info it should return.

**Comment by hoffmabc** [comment]
Pinging @strml

**Comment by theblacksquid** [comment]
After replacing `$PORT` and `$IP` with `process.env.PORT` and `process.env.IP` respectively, it doesn't give me an error anymore, but now it just doesn't do anything.

**Comment by reganlawton** [comment]
@theblacksquid why is your $PORT and $IP in quote string?

**Comment by STRML** [comment]
Yeah, this is a misunderstanding about how environment variables work in Node.

`"$IP"` is how you might import a variable from the environment in Bash, but in Node, that's `process.env.IP`.

Of course, it won't do anything if you don't have anything in your environment to begin with.

So use `var connector = require('openbazaar-connector')(process.env.IP, process.env.PORT);` if you intend to execute it like this:

`IP=localhost PORT=1234 node myApp.js`.
